### ISSUE TITLE
008

### ISSUE THREAD

**Issue by yusukeshib** [nukemenukeme/lesson#5]
1. 課題設定
2. 実装
3. 報告(苦労した点,出た疑問,習得した技術)

Due: 2016/07/29

**Comment by nukemenukeme** [comment]
・実装に苦労した点
　数学の基本的知識を思い出す必要がありました。主に回転の計算に使う三角関数です。
　Terminalなど、Macの基本的な操作に慣れていないので、gulpやnpmなどの操作に混乱しています。
　分解すると、自分の今わかっていない事は「プログラム」「数学」「コンピュータ操作」の3つに分けられると思いました。逆に、「プログラム的な考え方」や「コンピュータの設計思想」の部分については、比較的スッと理解できます。

・実装上で出た疑問
　「なんでこれで動くんだろう？」という疑問がずっとあります。
　htmlやcssでページを作ったとき、自分が書いた内容以上のことが起こっている（ように見える）ので、これは何かが裏で動いていたり、誰かが作ったシステムを自分が利用してるんだろうな、と思うのですが、じゃあそれはどういう仕組みなんだろう…ということがよくわかっていないので、気になってしまいます。めちゃくちゃ本とか読みたいです…

・習得した技術
　<h1>~<h6>、<p>、<a href=>、<class>など基本のhtmlの記述
　cssによるマージンやフォントの指定
　github及びgithub desktopの操作
　iPythonの操作、Vaporyライブラリを利用した3Dモデル描画
　ブラウザの検証機能の利用

**Comment by yusukeshib** [comment]
これ昨日までだよ？

**Comment by yusukeshib** [comment]
テキストはここに書かずにコミットしてもらったほうがいいかも。
